"""
PIHU WhatsApp MCP Server — FastMCP integration for WhatsApp messaging, contacts, and media.
"""

import os
import sys
import json
import sqlite3
import urllib.request
import urllib.error
from datetime import datetime
from typing import Optional, List, Dict, Any

try:
    from mcp.server.fastmcp import FastMCP
except ImportError:
    try:
        from mcp.server.mcpserver import MCPServer as FastMCP
    except ImportError:
        from mcp.server import FastMCP

mcp = FastMCP("PIHUWhatsAppMCP")

WHATSAPP_API_BASE_URL = os.getenv("PIHU_WHATSAPP_API_URL", "http://localhost:8080/api")


def resolve_messages_db_path() -> Optional[str]:
    """Find the SQLite messages database generated by the WhatsApp bridge."""
    candidates = [
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "pihu-whatsapp-mcp", "whatsapp-bridge", "store", "messages.db"),
        os.path.join(os.getcwd(), "src-tauri", "pihu_mcps", "mcp", "servers", "pihu-whatsapp-mcp", "whatsapp-bridge", "store", "messages.db"),
        os.path.join(os.getcwd(), "mcp", "servers", "pihu-whatsapp-mcp", "whatsapp-bridge", "store", "messages.db"),
        os.path.expanduser("~/.pihu/whatsapp/messages.db"),
        "store/messages.db",
    ]
    for p in candidates:
        if os.path.exists(p):
            return p
    return candidates[0]


def get_people_contacts() -> List[Dict[str, Any]]:
    """Load user-defined people and contacts from PIHU Settings storage."""
    paths = [
        os.path.expanduser("~/.pihu/contacts.json"),
        os.path.join(os.getcwd(), "src-tauri", "contacts.json"),
        os.path.join(os.getcwd(), "contacts.json"),
    ]
    for p in paths:
        if os.path.exists(p):
            try:
                with open(p, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    if isinstance(data, list):
                        return data
                    elif isinstance(data, dict) and "contacts" in data:
                        return data["contacts"]
            except Exception:
                pass
    return []


def resolve_recipient(recipient: str) -> str:
    """Resolve contact name or nickname to a valid phone number or JID."""
    if not recipient:
        return recipient
    
    clean = recipient.strip()
    if clean.isdigit() or "@" in clean:
        return clean
    
    # Check People directory
    people = get_people_contacts()
    clean_lower = clean.lower()
    for p in people:
        p_name = p.get("name", "").lower()
        p_nick = (p.get("nickname") or p.get("relationship", "")).lower()
        if clean_lower in p_name or (p_nick and clean_lower in p_nick):
            phone = p.get("phone", "")
            if phone:
                normalized = phone.replace("+", "").replace("-", "").replace(" ", "").replace("(", "").replace(")", "")
                if len(normalized) == 10 and normalized[0] in "6789":
                    normalized = "91" + normalized
                return normalized
    
    # Check live WhatsApp Bridge chats and groups
    try:
        req = urllib.request.Request(f"{WHATSAPP_API_BASE_URL}/chats", headers={"User-Agent": "PIHU-MCP"})
        with urllib.request.urlopen(req, timeout=1.5) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            for chat in data.get("chats", []):
                name = (chat.get("name") or "").lower()
                if clean_lower in name or name in clean_lower:
                    return chat.get("jid")
    except Exception:
        pass

    # Check WhatsApp database contacts fallback
    db_path = resolve_messages_db_path()
    if db_path and os.path.exists(db_path):
        try:
            conn = sqlite3.connect(db_path)
            cur = conn.cursor()
            cur.execute("SELECT jid FROM chats WHERE LOWER(name) LIKE ? LIMIT 1", (f"%{clean_lower}%",))
            row = cur.fetchone()
            conn.close()
            if row and row[0]:
                return row[0]
        except Exception:
            pass

    return clean


def api_request(endpoint: str, payload: Optional[Dict[str, Any]] = None, timeout: float = 8.0) -> Dict[str, Any]:
    """Execute HTTP request to the WhatsApp bridge REST API."""
    url = f"{WHATSAPP_API_BASE_URL}/{endpoint.lstrip('/')}"
    try:
        if payload is not None:
            data = json.dumps(payload).encode("utf-8")
            req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"}, method="POST")
        else:
            req = urllib.request.Request(url, method="GET")

        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read().decode("utf-8")
            return json.loads(body)
    except urllib.error.URLError as e:
        return {
            "success": False,
            "error": f"WhatsApp bridge offline at {url}. Error: {str(e)}. Run 'pihu mcp whatsapp auth' to start bridge.",
        }
    except Exception as e:
        return {"success": False, "error": str(e)}


@mcp.tool()
def whatsapp_send_message(recipient: str, message: str) -> Dict[str, Any]:
    """Send a WhatsApp text message to a person by name, nickname, phone number, or JID.

    Args:
        recipient: Name (e.g. 'Anin', 'Mayank'), phone number with country code (e.g. '919876543210'), or JID.
        message: The text content of the message to send.
    """
    resolved = resolve_recipient(recipient)
    res = api_request("send", {"recipient": resolved, "message": message})
    if res.get("success"):
        return {
            "status": "success",
            "recipient": resolved,
            "original_query": recipient,
            "message": f"WhatsApp message successfully delivered to {recipient} ({resolved})."
        }
    return {
        "status": "error",
        "recipient": resolved,
        "details": res.get("message") or res.get("error", "Unknown error sending WhatsApp message.")
    }


@mcp.tool()
def whatsapp_search_contacts(query: str) -> List[Dict[str, Any]]:
    """Search contacts across both WhatsApp conversation history and PIHU People directory.

    Args:
        query: Name, nickname, or phone number to search.
    """
    results = []
    q_lower = query.lower()

    # Search People directory
    for p in get_people_contacts():
        name = p.get("name", "")
        nick = p.get("nickname", "")
        phone = p.get("phone", "")
        email = p.get("email", "")
        if q_lower in name.lower() or (nick and q_lower in nick.lower()) or (phone and q_lower in phone):
            results.append({
                "name": name,
                "nickname": nick,
                "phone_number": phone,
                "email": email,
                "source": "PIHU People Directory",
                "notes": p.get("notes", "")
            })

    # Search WhatsApp database
    db_path = resolve_messages_db_path()
    if db_path and os.path.exists(db_path):
        try:
            conn = sqlite3.connect(db_path)
            cur = conn.cursor()
            cur.execute("""
                SELECT DISTINCT jid, name FROM chats
                WHERE (LOWER(name) LIKE ? OR jid LIKE ?) AND jid NOT LIKE '%@g.us'
                LIMIT 20
            """, (f"%{q_lower}%", f"%{q_lower}%"))
            for jid, name in cur.fetchall():
                results.append({
                    "name": name or jid.split("@")[0],
                    "phone_number": jid.split("@")[0],
                    "jid": jid,
                    "source": "WhatsApp Chats"
                })
            conn.close()
        except Exception:
            pass

    return results


@mcp.tool()
def whatsapp_list_messages(
    query: Optional[str] = None,
    sender_phone_number: Optional[str] = None,
    chat_jid: Optional[str] = None,
    limit: int = 15
) -> List[Dict[str, Any]]:
    """Get WhatsApp messages matching search criteria from local message store.

    Args:
        query: Text substring to search within message contents.
        sender_phone_number: Filter by sender phone number.
        chat_jid: Filter by chat JID.
        limit: Max messages to return (default 15).
    """
    db_path = resolve_messages_db_path()
    if not db_path or not os.path.exists(db_path):
        return [{"status": "info", "message": "No local WhatsApp messages database found. Connect WhatsApp via /mcp whatsapp auth."}]

    try:
        conn = sqlite3.connect(db_path)
        cur = conn.cursor()
        sql = """
            SELECT m.timestamp, m.sender, c.name, m.content, m.is_from_me, m.chat_jid, m.media_type
            FROM messages m
            LEFT JOIN chats c ON m.chat_jid = c.jid
        """
        where = []
        params = []
        if query:
            where.append("LOWER(m.content) LIKE LOWER(?)")
            params.append(f"%{query}%")
        if sender_phone_number:
            where.append("m.sender LIKE ?")
            params.append(f"%{sender_phone_number}%")
        if chat_jid:
            where.append("m.chat_jid = ?")
            params.append(chat_jid)

        if where:
            sql += " WHERE " + " AND ".join(where)
        sql += " ORDER BY m.timestamp DESC LIMIT ?"
        params.append(limit)

        cur.execute(sql, tuple(params))
        rows = cur.fetchall()
        conn.close()

        messages = []
        for r in rows:
            messages.append({
                "timestamp": r[0],
                "sender": r[1],
                "chat_name": r[2] or r[5],
                "content": r[3],
                "is_from_me": bool(r[4]),
                "chat_jid": r[5],
                "media_type": r[6]
            })
        return messages
    except Exception as e:
        return [{"error": str(e)}]


@mcp.tool()
def whatsapp_list_chats(limit: int = 15) -> List[Dict[str, Any]]:
    """List all active WhatsApp conversations and their last message timestamps.

    Args:
        limit: Max conversations to return (default 15).
    """
    db_path = resolve_messages_db_path()
    if not db_path or not os.path.exists(db_path):
        return []

    try:
        conn = sqlite3.connect(db_path)
        cur = conn.cursor()
        cur.execute("SELECT jid, name, last_message_time FROM chats ORDER BY last_message_time DESC LIMIT ?", (limit,))
        chats = []
        for row in cur.fetchall():
            chats.append({
                "jid": row[0],
                "name": row[1] or row[0].split("@")[0],
                "last_active": row[2],
                "is_group": row[0].endswith("@g.us")
            })
        conn.close()
        return chats
    except Exception:
        return []


@mcp.tool()
def whatsapp_get_last_interaction(contact_name_or_phone: str) -> Dict[str, Any]:
    """Get the most recent WhatsApp message exchanged with a specific person or phone number.

    Args:
        contact_name_or_phone: The name or phone number of the contact.
    """
    resolved = resolve_recipient(contact_name_or_phone)
    db_path = resolve_messages_db_path()
    if not db_path or not os.path.exists(db_path):
        return {"status": "error", "message": "WhatsApp message store not available."}

    try:
        conn = sqlite3.connect(db_path)
        cur = conn.cursor()
        cur.execute("""
            SELECT m.timestamp, m.sender, c.name, m.content, m.is_from_me
            FROM messages m
            JOIN chats c ON m.chat_jid = c.jid
            WHERE m.sender LIKE ? OR c.jid LIKE ? OR LOWER(c.name) LIKE ?
            ORDER BY m.timestamp DESC LIMIT 1
        """, (f"%{resolved}%", f"%{resolved}%", f"%{contact_name_or_phone.lower()}%"))
        row = cur.fetchone()
        conn.close()
        if row:
            return {
                "timestamp": row[0],
                "sender": row[1],
                "chat_name": row[2],
                "content": row[3],
                "is_from_me": bool(row[4])
            }
        return {"status": "not_found", "message": f"No recent messages found for {contact_name_or_phone}."}
    except Exception as e:
        return {"status": "error", "message": str(e)}


@mcp.tool()
def whatsapp_send_file(recipient: str, media_path: str) -> Dict[str, Any]:
    """Send an image, video, document, or audio file to a recipient via WhatsApp.

    Args:
        recipient: Name, phone number with country code, or JID.
        media_path: Absolute local filesystem path to the file.
    """
    resolved = resolve_recipient(recipient)
    if not os.path.isfile(media_path):
        return {"status": "error", "message": f"File not found on disk: {media_path}"}
    return api_request("send", {"recipient": resolved, "media_path": media_path})


@mcp.tool()
def whatsapp_download_media(message_id: str, chat_jid: str) -> Dict[str, Any]:
    """Download media attachments from a WhatsApp message to local storage.

    Args:
        message_id: The WhatsApp message ID containing media.
        chat_jid: The chat JID where the message was received.
    """
    return api_request("download", {"message_id": message_id, "chat_jid": chat_jid})


if __name__ == "__main__":
    mcp.run(transport="stdio")
